name: check

on:
  push:
  pull_request:

jobs:
  check:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4.2.2
      - name: ShellCheck
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y -qq shellcheck
          shellcheck install.sh tests/install_check.sh tests/publish_check.sh
      - name: Installer and publish checks
        run: bash ./tests/install_check.sh
